### ISSUE TITLE
Include a link either to CRAN or Quandl itself

### ISSUE THREAD

**Issue by dmpe** [quandl/quandl-r#37]
Meaning if there is such a possibility why not to use that then :)
Just not sure if to CRAN, Quandl or both ?

![q](https://cloud.githubusercontent.com/assets/1799661/8148923/fe176a84-12b1-11e5-8b28-5443ec540c0d.JPG)

**Comment by ccleung** [comment]
@dmpe thanks for the suggestion. we have added the CRAN link to the repo's description
