### ISSUE TITLE
Error: 301 moved permanently

### ISSUE THREAD

**Issue by hamm44** [quandl/quandl-r#43]
When I try to make a call on Quandl function using any code, for e.g
`Quandl("FRED/GDP")`

I get the following error message:

```
Error: <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

I'm using os x el capitan, have updated the quandl package.

**Comment by RaymondMcT** [comment]
Which version are you running?

packageVersion('Quandl')

**Comment by hamm44** [comment]
2.4.0

**Comment by hamm44** [comment]
I updated to R 3.22 and was able to upgrade quandl package to 2.7 and it works now.

Thanks.
