### ISSUE TITLE
Error when extracting data in xts

### ISSUE THREAD

**Issue by debsush** [quandl/quandl-r#49]
Hi,

Following is the error when I try to extract a specific Quandl dataset using xts.  It works fine when type = "raw".  

> Funddataset<-Quandl("DEB/MAWANASUG_A_SR",type="xts")
Warning message:
In zoo(data[, -1], frequency = freq, as.year(data[, 1])) :
  some methods for “zoo” objects do not work if the index entries in ‘order.by’ are not unique

I do not understand the issue with my code and why is zoo indexing by year and not date.  Please assist

Regards,
SD

**Comment by debsush** [comment]
I think the issue is the Quandl function 

      if(freq == 1) {
        data_out <- zoo(data[,-1], frequency = freq, as.year(data[,1]))
      } else if (freq == 4) {
        data_out <- zoo(data[,-1], frequency = freq, as.yearqtr(data[,1]))
      } else if (freq == 12) {
        data_out <- zoo(data[,-1], frequency = freq, as.yearmon(data[,1]))
      }

**Comment by ccleung** [comment]
Hi @debsush you are right. The dataset's metadata is labelling the data as [annual](https://www.quandl.com/api/v3/datasets/DEB/MAWANASUG_A_SR/metadata.json), but the data is actually not annual in frequency. Try `Quandl("DEB/MAWANASUG_A_SR",type="xts", force_irregular = TRUE)` and see if that works for you.

**Comment by debsush** [comment]
Thank you
