### ISSUE TITLE
Use of assignInNamespace

### ISSUE THREAD

**Issue by Sleepingwell** [quandl/quandl-r#5]
Lines 15, 34 and 42 of R/Quandl.R of use the function assignInNamespace. The documentation of that function notes that this should not be used in production code. Perhaps you would be better off setting an option: e.g., putting

    .onLoad <- function(libname, pkgname) {
        options(Quandl.auth_token=NA, Quandl.remaining_limit=NA)
    }

    .onUnload <- function(libpath) {
        options(Quandl.auth_token=NULL, Quandl.remaining_limit=NULL)
    }

in R/zzz.R

Then changing line 15 to

    options(Quandl.auth_token = auth_token)

line 34 to

     options(Quandl.auth_token = remaining_limit)

and line 42 to

    options(Quandl.remaining_limit = headers$value()[["X-RateLimit-Remaining"]])

**Comment by RaymondMcT** [comment]
Fixed in version 2.7.0.
