### ISSUE TITLE
Can't retrieve stock information

### ISSUE THREAD

**Issue by DanielStay** [quandl/quandl-r#51]
Hello everyone,

i've been trying to use quandl R today to make a simple request for a certain stock. However the function always returned the error: Error: All components of query must be named. I'm using Quandl version 2.6.0 in RStudio Version 0.99.892

I've authenticated myself with the Quandl.auth function (with my API key):
Quandl.auth("")

and requested the following stock: 

my data<-Quandl("OPEC/ORB") (from the homepage)

Could you please tell me how I can solve this issue?

**Comment by DanielStay** [comment]
The Issue has been solved. Quandl.auth("") needed to be changed to Quandl.api_key()

**Comment by michaelfich** [comment]
Hey Daniel.

Thanks for getting back to us.  I’m glad to see you were able to get this issue resolved.  If you encounter any further issues, please feel free to reach out again.
