### ISSUE TITLE
Stocks with special characters are not fetching data.

### ISSUE THREAD

**Issue by Pruthvi79chow** [quandl/quandl-r#59]
In few stock names of NSE we have a special character(&) Ampersand. While pulling such information code is throwing following error. 

`quandldata = Quandl("NSE/M&M", collapse="daily", limit=1)`
**Error in format.code(code) : 
  Codes are comprised of capital letters, numbers and underscores only.**
 
Is there any workaround to pull information from such stocks?

**Comment by mbasset** [comment]
Hi @Pruthvi79chow,

For compatibility reasons we don't support the `&` character in our API calls. However it looks like the stock you are looking for might be:

https://www.quandl.com/data/NSE/MM-Mahindra-Mahindra-Limited

For stocks like this that include special characters you can use our system to search through the metadata of companies via the search interface for that data product. (ex: https://www.quandl.com/data/NSE-National-Stock-Exchange-of-India). Additionally you can confirm whether a code exists with the codes list found here https://www.quandl.com/data/NSE-National-Stock-Exchange-of-India/usage/export
