### ISSUE TITLE
'names' attribute [7] must be the same length as the vector [5] when trying to get dataset

### ISSUE THREAD

**Issue by anamariamocanu** [quandl/quandl-r#62]
Hello,

I am trying to get this data Quandl("GPP/CFP_NZL", start_date= "2019-01-01", end_date="2019-10-14") but I keep getting this error: 

Error in names(data) <- json$column_names : 
  'names' attribute [7] must be the same length as the vector [5]

It works with one column index but not with the full dataset or date ranges.

Thanks!
Ana

**Comment by ericvautour-quandl** [comment]
Hello Ana,

Thank you for your inquiry and I do apologize for the late response.  After investigating the issue we have determined that the data in question is deprecated.  As a result it will not be handled properly by our R package when requesting the full dataset.

We apologize for the inconvenience.
Sincerely,
Eric
